apiVersion: v1
kind: PersistentVolume
metadata:
  name: repos-github-server
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/repos"
